# Generated by Django 2.0 on 2018-10-16 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmitirCertificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt_falta', models.CharField(max_length=3, verbose_name='Quantidade de faltas')),
                ('emitir_cert', models.IntegerField(choices=[(0, 'Autorizo'), (1, 'Não autorizo')], help_text='Deseja autorizar a emissão do certificado para o respectivo usuário', verbose_name='Emissão do certificado')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.PositiveIntegerField()),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=4)),
                ('cpf', models.PositiveIntegerField()),
                ('rg', models.PositiveIntegerField()),
                ('telefone', models.CharField(max_length=15)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.Evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscrito',
                'verbose_name_plural': 'Inscritos',
                'db_table': 'inscrito',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Evento')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Responsavel',
                'verbose_name_plural': 'Responsaveis',
                'db_table': 'responsavel',
            },
        ),
        migrations.AddField(
            model_name='emitircertificado',
            name='inscrito',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Inscrito'),
        ),
    ]
