# Generated by Django 2.0 on 2018-11-01 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emitircertificado',
            options={'ordering': ('-inscrito',), 'verbose_name': 'Emitir certificado', 'verbose_name_plural': 'Emitir certificados'},
        ),
        migrations.AlterField(
            model_name='emitircertificado',
            name='inscrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscrito', to='cadastro.Inscrito'),
        ),
        migrations.AlterModelTable(
            name='emitircertificado',
            table='emitircertificado',
        ),
    ]
