# Generated by Django 2.0 on 2018-10-23 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181023_0207'),
        ('cadastro', '0002_auto_20181022_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.PositiveIntegerField()),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=4)),
                ('cpf', models.PositiveIntegerField()),
                ('rg', models.PositiveIntegerField()),
                ('telefone', models.CharField(max_length=15)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscrito',
                'verbose_name_plural': 'Inscritos',
                'db_table': 'inscrito',
            },
        ),
    ]
