# Generated by Django 2.0 on 2018-11-01 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20181101_0201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emitircertificado',
            options={'verbose_name': 'Emitir certificado', 'verbose_name_plural': 'Emitir certificados'},
        ),
        migrations.AlterModelOptions(
            name='inscrito',
            options={'ordering': ('nome',), 'verbose_name': 'Inscrito', 'verbose_name_plural': 'Inscritos'},
        ),
    ]
