# Generated by Django 2.0 on 2018-09-24 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20180920_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmitirCertificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt_falta', models.CharField(max_length=3)),
                ('emitir_cert', models.IntegerField(choices=[(0, 'Autorizo'), (1, 'Não autorizo')], help_text='Deseja autorizar a emissão do certificado para o respectivo usuário', verbose_name='Emissão do certificado')),
                ('inscrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Inscrito')),
            ],
        ),
    ]
