# Generated by Django 2.0 on 2018-11-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20181101_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='ministrante',
            field=models.CharField(max_length=100, verbose_name='Ministrante'),
        ),
    ]
