# Generated by Django 2.0.6 on 2018-08-13 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.PositiveIntegerField()),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=4)),
                ('cpf', models.PositiveIntegerField()),
                ('rg', models.PositiveIntegerField()),
                ('telefone', models.CharField(max_length=15)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inscritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inscrito',
                'verbose_name_plural': 'Inscritos',
                'verbose_name': 'Inscrito',
            },
        ),
    ]
