# Generated by Django 2.0 on 2018-10-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='edicao_atual',
            new_name='edicao',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='edicao_anterior',
        ),
    ]
