# Generated by Django 2.0 on 2018-09-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='carga_h',
            field=models.CharField(default=11, max_length=5, verbose_name='Carga horaria prevista'),
            preserve_default=False,
        ),
    ]
