# Generated by Django 2.0 on 2018-11-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='imagem',
            field=models.ImageField(upload_to='imagem', verbose_name='Imagem'),
        ),
    ]
