# Generated by Django 2.0 on 2018-11-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ('data_public',), 'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
    ]
