# Generated by Django 2.0 on 2018-10-23 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181022_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscrito',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='inscrito',
        ),
        migrations.DeleteModel(
            name='Inscrito',
        ),
    ]
