# Generated by Django 2.0 on 2018-10-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181017_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='slug',
        ),
    ]
