# Generated by Django 2.0 on 2018-10-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181001_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='edicao_anterior',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
